name: CI/CD Workflow for fm Branch

on:
  push:
    branches:
      - fm

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Start the web app in the background
      - name: Start web app
        run: |
          npm run dev &
          sleep 10

      # Check if the web app is running
      - name: Health check
        run: |
          curl -f http://localhost:5173 || exit 1

      # Stop the web app
      - name: Stop web app
        run: |
          pkill -f "npm run dev" || true

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Git
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Merge fm into main
      - name: Merge fm into main
        run: |
          git fetch origin main
          git checkout main
          git merge fm --allow-unrelated-histories || (
            git add . &&
            git commit -m "Merge fm with automatically with CI/CD"
          )
          git push origin main